CREATE TABLE IF NOT EXISTS SEARCH(
    ID               IDENTITY NOT NULL PRIMARY KEY,
    NAME             VARCHAR,
    URL              VARCHAR,
    DOWNLOADCOUNT    VARCHAR,
    START            VARCHAR
);

CREATE TABLE IF NOT EXISTS ADS(
	ID          IDENTITY NOT NULL PRIMARY KEY,
	SEARCH      BIGINT REFERENCES SEARCH(ID),
	HREF        VARCHAR,
	TITLE       VARCHAR,
	DESCRIPTION VARCHAR,
	PRICE       VARCHAR,
	BRIEF       VARCHAR,
	HTML        VARCHAR
);

